/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.cassandra.thrift;
/*
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 */


import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MultigetSliceResult implements org.apache.thrift.TBase<MultigetSliceResult, MultigetSliceResult._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MultigetSliceResult");

  private static final org.apache.thrift.protocol.TField VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("value", org.apache.thrift.protocol.TType.MAP, (short)1);
  private static final org.apache.thrift.protocol.TField DV_FIELD_DESC = new org.apache.thrift.protocol.TField("dv", org.apache.thrift.protocol.TType.LIST, (short)2);

  public Map<ByteBuffer,List<ColumnOrSuperColumn>> value; // required
  public List<Long> dv; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VALUE((short)1, "value"),
    DV((short)2, "dv");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VALUE
          return VALUE;
        case 2: // DV
          return DV;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VALUE, new org.apache.thrift.meta_data.FieldMetaData("value", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , true), 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ColumnOrSuperColumn.class)))));
    tmpMap.put(_Fields.DV, new org.apache.thrift.meta_data.FieldMetaData("dv", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.LIST        , "VectorClock")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MultigetSliceResult.class, metaDataMap);
  }

  public MultigetSliceResult() {
  }

  public MultigetSliceResult(
    Map<ByteBuffer,List<ColumnOrSuperColumn>> value,
    List<Long> dv)
  {
    this();
    this.value = value;
    this.dv = dv;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MultigetSliceResult(MultigetSliceResult other) {
    if (other.isSetValue()) {
      Map<ByteBuffer,List<ColumnOrSuperColumn>> __this__value = new HashMap<ByteBuffer,List<ColumnOrSuperColumn>>();
      for (Map.Entry<ByteBuffer, List<ColumnOrSuperColumn>> other_element : other.value.entrySet()) {

        ByteBuffer other_element_key = other_element.getKey();
        List<ColumnOrSuperColumn> other_element_value = other_element.getValue();

        ByteBuffer __this__value_copy_key = org.apache.thrift.TBaseHelper.copyBinary(other_element_key);
;

        List<ColumnOrSuperColumn> __this__value_copy_value = new ArrayList<ColumnOrSuperColumn>();
        for (ColumnOrSuperColumn other_element_value_element : other_element_value) {
          __this__value_copy_value.add(new ColumnOrSuperColumn(other_element_value_element));
        }

        __this__value.put(__this__value_copy_key, __this__value_copy_value);
      }
      this.value = __this__value;
    }
    if (other.isSetDv()) {
      this.dv = other.dv;
    }
  }

  public MultigetSliceResult deepCopy() {
    return new MultigetSliceResult(this);
  }

  @Override
  public void clear() {
    this.value = null;
    this.dv = null;
  }

  public int getValueSize() {
    return (this.value == null) ? 0 : this.value.size();
  }

  public void putToValue(ByteBuffer key, List<ColumnOrSuperColumn> val) {
    if (this.value == null) {
      this.value = new HashMap<ByteBuffer,List<ColumnOrSuperColumn>>();
    }
    this.value.put(key, val);
  }

  public Map<ByteBuffer,List<ColumnOrSuperColumn>> getValue() {
    return this.value;
  }

  public MultigetSliceResult setValue(Map<ByteBuffer,List<ColumnOrSuperColumn>> value) {
    this.value = value;
    return this;
  }

  public void unsetValue() {
    this.value = null;
  }

  /** Returns true if field value is set (has been assigned a value) and false otherwise */
  public boolean isSetValue() {
    return this.value != null;
  }

  public void setValueIsSet(boolean value) {
    if (!value) {
      this.value = null;
    }
  }

  public int getDvSize() {
    return (this.dv == null) ? 0 : this.dv.size();
  }

  public java.util.Iterator<Long> getDvIterator() {
    return (this.dv == null) ? null : this.dv.iterator();
  }

  public void addToDv(long elem) {
    if (this.dv == null) {
      this.dv = new ArrayList<Long>();
    }
    this.dv.add(elem);
  }

  public List<Long> getDv() {
    return this.dv;
  }

  public MultigetSliceResult setDv(List<Long> dv) {
    this.dv = dv;
    return this;
  }

  public void unsetDv() {
    this.dv = null;
  }

  /** Returns true if field dv is set (has been assigned a value) and false otherwise */
  public boolean isSetDv() {
    return this.dv != null;
  }

  public void setDvIsSet(boolean value) {
    if (!value) {
      this.dv = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VALUE:
      if (value == null) {
        unsetValue();
      } else {
        setValue((Map<ByteBuffer,List<ColumnOrSuperColumn>>)value);
      }
      break;

    case DV:
      if (value == null) {
        unsetDv();
      } else {
        setDv((List<Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VALUE:
      return getValue();

    case DV:
      return getDv();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VALUE:
      return isSetValue();
    case DV:
      return isSetDv();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MultigetSliceResult)
      return this.equals((MultigetSliceResult)that);
    return false;
  }

  public boolean equals(MultigetSliceResult that) {
    if (that == null)
      return false;

    boolean this_present_value = true && this.isSetValue();
    boolean that_present_value = true && that.isSetValue();
    if (this_present_value || that_present_value) {
      if (!(this_present_value && that_present_value))
        return false;
      if (!this.value.equals(that.value))
        return false;
    }

    boolean this_present_dv = true && this.isSetDv();
    boolean that_present_dv = true && that.isSetDv();
    if (this_present_dv || that_present_dv) {
      if (!(this_present_dv && that_present_dv))
        return false;
      if (!this.dv.equals(that.dv))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_value = true && (isSetValue());
    builder.append(present_value);
    if (present_value)
      builder.append(value);

    boolean present_dv = true && (isSetDv());
    builder.append(present_dv);
    if (present_dv)
      builder.append(dv);

    return builder.toHashCode();
  }

  public int compareTo(MultigetSliceResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MultigetSliceResult typedOther = (MultigetSliceResult)other;

    lastComparison = Boolean.valueOf(isSetValue()).compareTo(typedOther.isSetValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value, typedOther.value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDv()).compareTo(typedOther.isSetDv());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDv()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dv, typedOther.dv);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // VALUE
          if (field.type == org.apache.thrift.protocol.TType.MAP) {
            {
              org.apache.thrift.protocol.TMap _map104 = iprot.readMapBegin();
              this.value = new HashMap<ByteBuffer,List<ColumnOrSuperColumn>>(2*_map104.size);
              for (int _i105 = 0; _i105 < _map104.size; ++_i105)
              {
                ByteBuffer _key106; // required
                List<ColumnOrSuperColumn> _val107; // required
                _key106 = iprot.readBinary();
                {
                  org.apache.thrift.protocol.TList _list108 = iprot.readListBegin();
                  _val107 = new ArrayList<ColumnOrSuperColumn>(_list108.size);
                  for (int _i109 = 0; _i109 < _list108.size; ++_i109)
                  {
                    ColumnOrSuperColumn _elem110; // required
                    _elem110 = new ColumnOrSuperColumn();
                    _elem110.read(iprot);
                    _val107.add(_elem110);
                  }
                  iprot.readListEnd();
                }
                this.value.put(_key106, _val107);
              }
              iprot.readMapEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // DV
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list111 = iprot.readListBegin();
              this.dv = new ArrayList<Long>(_list111.size);
              for (int _i112 = 0; _i112 < _list111.size; ++_i112)
              {
                long _elem113; // required
                _elem113 = iprot.readI64();
                this.dv.add(_elem113);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.value != null) {
      oprot.writeFieldBegin(VALUE_FIELD_DESC);
      {
        oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.LIST, this.value.size()));
        for (Map.Entry<ByteBuffer, List<ColumnOrSuperColumn>> _iter114 : this.value.entrySet())
        {
          oprot.writeBinary(_iter114.getKey());
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter114.getValue().size()));
            for (ColumnOrSuperColumn _iter115 : _iter114.getValue())
            {
              _iter115.write(oprot);
            }
            oprot.writeListEnd();
          }
        }
        oprot.writeMapEnd();
      }
      oprot.writeFieldEnd();
    }
    if (this.dv != null) {
      oprot.writeFieldBegin(DV_FIELD_DESC);
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, this.dv.size()));
        for (long _iter116 : this.dv)
        {
          oprot.writeI64(_iter116);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MultigetSliceResult(");
    boolean first = true;

    sb.append("value:");
    if (this.value == null) {
      sb.append("null");
    } else {
      sb.append(this.value);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dv:");
    if (this.dv == null) {
      sb.append("null");
    } else {
      sb.append(this.dv);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

